server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://175.125.23.122:8761/eureka
    enabled: true
rest:
  version: v1.0
spring:
  profiles:
    active: local
  application:
    name: green-device
  main:
    allow-bean-definition-overriding: true
---
spring:
  profiles: local
  # jdbc
  datasource:
    hikari:
      # jdbc-master
      master:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://175.125.23.122:3306/MASTER
        username: master
        password: green!!20master
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        maximumPoolSize: 20
        minimumIdle: 10
#mybatis config
mybatis:
  config-location: classpath:mybatis/mariadb/MapperConfig.xml
---
spring:
  profiles: dev
  # datasource
  datasource:
    # jdbc-master
    hikari:
      master:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://175.125.23.122:3306/MASTER
        username: master
        password: green!!20master
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        maximumPoolSize: 20
        minimumIdle: 10
#mybatis config
mybatis:
  config-location: classpath:mybatis/mariadb/MapperConfig.xml