server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.10.191:8761/eureka
    enabled: true
spring:
  profiles:
    active: local
  application:
    name: green-device
  main:
    allow-bean-definition-overriding: true
---
spring:
  profiles: local
  # jdbc
  datasource:
    hikari:
      # jdbc-master
      master:
        dirver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://172.16.10.191:3306/MASTER
        username: master
        password: green!!20master
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        maximumPoolSize: 20
        minimumIdle: 10
---
spring:
  profiles: dev
  # datasource
  datasource:
    # jdbc-master
    hikari:
      master:
        dirver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://172.16.10.191:3306/MASTER
        username: master
        password: green!!20master
        idleTimeout: 10000
        connection-timeout: 10000
        validation-timeout: 10000
        maxLifetime: 580000
        maximumPoolSize: 20
        minimumIdle: 10